apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-db
  labels:
    app: mongodb
spec:
  replicas: 3
  selector:
    matchLabels:
      name: test-db
  serviceName: test-db-svc
  template:
    metadata:
      labels:
        name: test-db
        app: mongodb
    spec:
      containers:
      - name: test-db
        image: quay.io/mongodb/mongodb-enterprise-appdb:10.2.15.5958-1
        ports:
        - containerPort: 27017
        env:
        - name: HEADLESS_AGENT
          value: "true"
        - name: AUTOMATION_CONFIG_MAP
          value: "test-db-config"
        volumeMounts:
        - mountPath: /var/lib/mongodb-automation/
          name: cluster-config
          readOnly: true
      volumes:
      - configMap:
          defaultMode: 420
          name: test-db-config
        name: cluster-config
